### ISSUE TITLE
Cannot install and run on Centos 6

### ISSUE THREAD

**Issue by bimemto** [Daplie/pokemap-webapp#1]
Error: /Documents/workspace/pokemap/node_modules/s2geometry-node/build/Release/NativeExtension.node: invalid ELF header

**Comment by anton101101** [comment]
Hi,

I'am also having the same error. Running Ubuntu 14.04.4

Error: /opt/pokemap/node_modules/s2geometry-node/build/Release/NativeExtension.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (/opt/pokemap/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/pokemap/node_modules/s2geometry-node/index.js:1:104)
    at Module._compile (module.js:541:32)

Thanks

**Comment by coolaj86** [comment]
Unfortunately until I can resolve this problem (https://github.com/Daplie/node-pokemap/issues/7), the package that I made won't work for everyone. :-/

However, if you follow the *slightly* more technical instructions at https://github.com/Daplie/node-pokemap it should work without a hitch.

**Comment by anton101101** [comment]
Thanks dude will give it a try.

**Comment by anton101101** [comment]
I got your server running I have put my google api key into the config file but when I go to  http://127.0.0.1:3000 I cant seem to login with my ptc account. 

cli output   **[i] Logging with user:  XX**

https://gyazo.com/5e095b9cb1d0513fd0f65ef2f6b4eaf4

Also does this support multiple users if so is it via them logging in or does it use the one account?

Thanks

Anton

**Comment by coolaj86** [comment]
I'd need to see the logs from the client (meaning Chrome, Firefox, etc).

Some of the code is still in ES6 (I would like help fixing this), which prevents it from working in some browsers which only support ES5.1.

It supports multiple users, you shouldn't login with users that are in very different geographic locations (i.e. outside of your city or state).

Essentially if you are going to have a bunch of people that are using the server with you they should be people in your group out hunting together, otherwise the IP will get a soft short-term ban.

Also, try installing the latest by following these instructions: https://github.com/Daplie/node-pokemap

**Comment by coolaj86** [comment]
Fixed with https://github.com/Daplie/node-pokemap/issues/7 in v1.1.1
